--AUTHORITIES BEGIN--
INSERT INTO authority values (1, 'ROLE_REG_CUSTOMER');
INSERT INTO authority values (2, 'ROLE_COMPANY_OWNER');
INSERT INTO authority values (3, 'ROLE_ADMIN');

--AUTHORITIES END--